version: 2
updates:
  - package-ecosystem: docker
    directories: ["/docker/nginx", "/docker/php-fpm"]
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
